<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="santhoshp-lt" name="orangehrma.HrmMain" tests="8" failures="0" timestamp="5 Nov 2013 10:23:43 GMT" time="214.278" errors="1">
  <testcase name="TestMethod1" time="16.711" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod8" time="26.559" classname="orangehrma.HrmMain">
    <error type="java.lang.AssertionError" message="Element could not be found, Employee name entry should exist inorder to delete it expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Element could not be found, Employee name entry should exist inorder to delete it expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at orangehrma.HrmMain.TestMethod8(HrmMain.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- TestMethod8 -->
  <testcase name="TestMethod2" time="30.084" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod3" time="27.448" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod4" time="24.757" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod5" time="31.143" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod7" time="28.115" classname="orangehrma.HrmMain"/>
  <testcase name="TestMethod6" time="29.461" classname="orangehrma.HrmMain"/>
</testsuite> <!-- orangehrma.HrmMain -->
